# Generated by Django 5.2.15 on 2026-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(upload_to='profile/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bio',
            },
        ),
    ]
